version: '3.9'

volumes:
  postgres-intelectronica-test-data:

services:
  intelectronica-test-db:
    container_name: intelectronica-test-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-intelectronica-test-data:/var/lib/postgresql/data
    networks:
      - intelectronica-net
networks:
  intelectronica-net: